### ISSUE TITLE
firmware cannode-v1 not fit in flash

### ISSUE THREAD

**Issue by qbazd** [PX4/UAVCAN_Bootloaders#4]
Hello,

I'm trying to build bootloader for PX4 cannode-v1 and:

arm-none-eabi/bin/ld: px4cannode-v1.elf section `.text' will not fit in region `flash'
arm-none-eabi/bin/ld: region `flash' overflowed by 62 bytes

I'm using toolchain version from documentation GCC 7-2017-q4 
https://dev.px4.io/v1.9.0/en/setup/dev_env_linux_ubuntu.html
on Ubuntu 16.04.6

I've checked out latest commit and commit named "All targets fit in FLASH".
Overflow is the same: 62 bytes.

I assume that system or toolchain differs.

Any idea where to start resolving issue?
On what system/toolchain will it fit 8K?

Best regards.
Jakub Zdroik

**Comment by nunolucas** [comment]
For others with the some problem, using `gcc-arm-none-eabi-5_3-2016q1` solved this for me without any changes.

Later versions require the cmake script to ensure LTO is enabled, but I have no cmake-foo powers to dare to advise anyone on this (I can hack a fix to the 2017q1 version by forcing the commented "-flto" line on `add_compile_options`).

**Comment by davids5** [comment]
Please ONLY use what is listed in the [CI  containers](https://github.com/PX4/PX4-containers/blob/2e36291bcc858d5b6a5b70971c147ac69c373b3d/docker/Dockerfile_nuttx-focal#L30)


 https://developer.arm.com/-/media/Files/downloads/gnu-rm/9-2020q2/gcc-arm-none-eabi-9-2020-q2-update-x86_64-linux.tar.bz2

**Comment by nunolucas** [comment]
I see. Please forget anything I said. My use-case is outside of the PX4 environment.

I do find it hilarious that was needed for [someone to be wrong on the internet](https://xkcd.com/386/) for a 2 year old issue to be answered ;-)

**Comment by davids5** [comment]
This is an obsolete repo the UAVCAN bootloaders are now in-tree in PX4.
